### ISSUE TITLE
会支持One-time authentication 吗

### ISSUE THREAD

**Issue by ztechie** [qiuyuzhou/ShadowsocksX-NG#1]
会支持One-time authentication 吗

**Comment by qiuyuzhou** [comment]
已经支持了，你可要测试下。

**Comment by ztechie** [comment]
dmg程序有么

2016-06-12 19:58 GMT+08:00 Qiu Yuzhou <notifications@github.com>:

**Comment by zcracker** [comment]
可以提供dmg吗谢谢

2016-06-12 20:04 GMT+08:00 zcrackery@gmail.com:

**Comment by ztechie** [comment]
可否提供dmg版本？我来测试


发自 网易邮箱大师
在2016年06月12日 19:58，Qiu Yuzhou 写道:

已经支持了，你可要测试下。
