### ISSUE TITLE
Cannot open v1.9.4 on macOS catalina 10.15.1

### ISSUE THREAD

**Issue by xhj-fs** [qiuyuzhou/ShadowsocksX-NG#1196]
OS: macOS catalina 10.15.1
Error Message:
'ShadowsocksX-NG cannot be opened because Apple cannot check it for malicious software'

Appreciate your assistance!

**Comment by x1aolong** [comment]
You may be required to create folders manually  

mkdir ~/.ShadowsocksX-NG

**Comment by xhj-fs** [comment]
Hi thanks for the suggestion, I alr have the folder and the problem still exists.
