### ISSUE TITLE
有没有IOS版的小飞机啊？？？给个传送门

### ISSUE THREAD

**Issue by GZK0329** [qiuyuzhou/ShadowsocksX-NG#1198]
有没有IOS版的小飞机啊？？？给个传送门

**Comment by anticpc** [comment]
Shadowrocket / Quan

**Comment by Crescentz** [comment]
app store搜不到Shadowrocket

**Comment by AidanFreeman** [comment]
下一个wingy

Learning入门 <notifications@github.com> 于2019年12月11日周三 上午9:56写道：
