### ISSUE TITLE
能增加使用在线pac的功能吗？

### ISSUE THREAD

**Issue by shenhix** [qiuyuzhou/ShadowsocksX-NG#12]
Safari好像没有类似chrome上 SwitchyOmega 的代理管理插件，所以有时候会用到在线的pac，不知道 能不能增加这个功能！

**Comment by qiuyuzhou** [comment]
Sorry,我没有明白你的意思。
在系统里配置自动代理设置后，safari是可以使用设置的pac脚本的。
你可以详细描述你的使用场景吗？

**Comment by shenhix** [comment]
不好意思，我没说明白。
如果打开ShadowsocksX，在系统网络里时不能设置在线pac的，如果食用了在线pac，ShadowsocksX又不能使用，我的想法是是否可以在服务器中增加一个在线pac的功能，这样切换起来非常方便!

**Comment by qiuyuzhou** [comment]
如果不想ss设置系统代理设置，可以使用手动模式。需要你手工或通过其他方式配置代理指向ss客户端开启的本地socks5代理。

一般pac文件里都有指定代理服务器地址。类似：

`var proxy = "SOCKS5 127.0.0.1:1086; SOCKS 127.0.0.1:1086; DIRECT;";`

不知道你说的在线pac是指什么？

**Comment by shenhix** [comment]
@qiuyuzhou 现在有些FQ的网站提供在线的PAC代理，类似（https://pac.itzmx.com/）这样的，应该属于http代理的模式。也很方便但是不能配合SS的客户端一起使用！
您说的手工模式我知道，我在WIN平台使用chrome的时候用SwitchyOmega 插件就很方便，用这个插件来调用SS或者在线PAC，但是safari没有类似的插件= =！ 
不知道作者您有没有方法能在SS客户端里面加入这个功能！！

**Comment by qiuyuzhou** [comment]
你的需求是否是：有一个方便的方法在ss客户端代理和其他外部代理之间进行方便的切换？还是你需要向SwitchyOmega一样，使用可配置的规则将访问导向不同代理？

**Comment by shenhix** [comment]
@qiuyuzhou 这两个需求不是一样吗？  我觉得你做的这个SS客户端很好，能否在程序内添加一个切换在线PAC的功能，就像SS切换服务器一样！ 如果做到配置规则导向不同代理，那工作量应该太大了，而且也有类似的工具！  比如COW之类的，只是小白一枚，不喜欢花功夫，如果能有个方便的软件就非常感谢了！

**Comment by shenhix** [comment]
@qiuyuzhou 只是希望在客户端里增加一个切换SS服务器和在线PAC代理的功能！  不知道能不能实现！

**Comment by ConnersHua** [comment]
他的意思是，现在的客户端是内置了 GFWList 的链接，使用时还需要下载下来，他想要一个类似 Windows 平台上 ShadowsocksR 那样的可以直接填写 PAC 链接并直接使用的功能。

**Comment by lazze** [comment]
这个文件怎么这么大啊 ？@qiuyuzhou

**Comment by qiuyuzhou** [comment]
哪个文件？

lazze <notifications@github.com>于2016年7月25日 周一下午4:09写道：

**Comment by lazze** [comment]
下载下来的包 5mb  以前的也就几百K @qiuyuzhou

**Comment by qiuyuzhou** [comment]
@ConnersHua 我的理解是他想使用其他代理，只是要用shadowsocksx-ng去管理代理配置切换。代理服务器配置是在pac文件中的，所以在线pac文件是无法指向本地代理的。

**Comment by qiuyuzhou** [comment]
@lazze 现在就是这么大。实现方式不一样，实现语言不一样，用到库不一样。
顺便说下，你歪楼了。

**Comment by shenhix** [comment]
谢谢大家的回答！
