### ISSUE TITLE
安装后不能打开

### ISSUE THREAD

**Issue by DukeFox** [qiuyuzhou/ShadowsocksX-NG#1206]
![2.jpg](https://i.loli.net/2019/11/20/Sk8OhjcR71WsVDd.jpg)

解压后拖进应用程序后，打开提示不能打开，参考之前的Issues后，安装1.9.2再覆盖安装最新版之后打开还是一样的提示。

安全性与隐私里面，“任何来源”的选项也已经勾上了。

系统版本：
![1.jpg](https://i.loli.net/2019/11/20/feg4EIR3No6nGO9.jpg)

**Comment by molandao** [comment]
我的10.15也打不开

**Comment by obarong** [comment]
打开app弹出错误后，到安全性与隐私-通用，下面有按钮可以允许打开。

**Comment by DukeFox** [comment]
> 打开app弹出错误后，到安全性与隐私-通用，下面有按钮可以允许打开。

一样的，还是“不能打开”，目前已经换成老版本了，可以正常使用。

**Comment by LangYa1945** [comment]
@DukeFox 老版本是多少呀，我的还是不能用
