### ISSUE TITLE
catalina 10.15 无法联网

### ISSUE THREAD

**Issue by spytensor** [qiuyuzhou/ShadowsocksX-NG#1213]
有人解决吗？手机端、windows都可以用

**Comment by yudefreesky** [comment]
一样，无法上网

**Comment by yudefreesky** [comment]
ShadowsocksX-NG-R8无法上网

**Comment by yudefreesky** [comment]
已经解决

**Comment by yudefreesky** [comment]
[![QFUPcd.jpg](https://s2.ax1x.com/2019/11/28/QFUPcd.jpg)](https://imgchr.com/i/QFUPcd)
[![QFU99e.md.jpg](https://s2.ax1x.com/2019/11/28/QFU99e.md.jpg)](https://imgchr.com/i/QFU99e)

**Comment by yudefreesky** [comment]
以后记得关电脑的时候先退出所有运行的软件
[![QFUC1H.md.jpg](https://s2.ax1x.com/2019/11/28/QFUC1H.md.jpg)](https://imgchr.com/i/QFUC1H)

**Comment by yudefreesky** [comment]
深藏功与名，晚安

**Comment by yudefreesky** [comment]
貌似不能彻底解决问题

**Comment by yudefreesky** [comment]
现在可以访问谷歌的图片给你看下参考

**Comment by yudefreesky** [comment]
[![QFw8HI.md.jpg](https://s2.ax1x.com/2019/11/28/QFw8HI.md.jpg)](https://imgchr.com/i/QFw8HI)
[![QFw3DA.md.jpg](https://s2.ax1x.com/2019/11/28/QFw3DA.md.jpg)](https://imgchr.com/i/QFw3DA)

**Comment by yudefreesky** [comment]
可以试一下不同的节点，我可以正常上网了

**Comment by Janejxt** [comment]
> 可以试一下不同的节点，我可以正常上网了

我用你的方法，重启后，使用全局模式好了，然后切回pac也好了，谢谢

**Comment by spytensor** [comment]
我还是不行。。。。

**Comment by spytensor** [comment]
原来需要配置插件。。。

**Comment by XiaoLaoDi** [comment]
@spytensor 能麻烦把具体步骤再说一下嘛？我这还是不行

**Comment by Janejxt** [comment]
> @spytensor 能麻烦把具体步骤再说一下嘛？我这还是不行

就按照他上面的截图配置啊，里面的端口号要和你shadowsock里的配置信息一样就行，他上面是1088，我的上面是1086，你看你自己的是多少，然后按照他图的步骤 配置一下就好了。

**Comment by ShaocongZheng** [comment]
@yudefreesky 
图挂了老哥，你是怎么解决的
