### ISSUE TITLE
测速是测哪里的延迟?

### ISSUE THREAD

**Issue by mqliutie** [qiuyuzhou/ShadowsocksX-NG#1233]
![image](https://user-images.githubusercontent.com/11795518/71611719-6b373f80-2bd6-11ea-8eb0-995e6899226b.png)

服务器测速按钮, 按了后各代理的延迟都在后面跟着显示.

我 `ping` 了下这个`香港4`的节点, 发现差不多就是`90ms`左右, 所以这个延迟是不是代表我和这个代理的连通性?

但是他不保证连到这个服务后这个服务是否和`google`连通, 以及这个节点和`google`之间的延迟. 

有什么办法能保证这个节点和google是否通得嘛? 能不能提前检测?

**Comment by meteormatt** [comment]
你的软件不是ShadowsocksX-NG，而是ShadowsocksX-NG-R
https://github.com/qinyuhang/ShadowsocksX-NG-R

**Comment by mqliutie** [comment]
哦哦 这样啊
