### ISSUE TITLE
怎么把某个网站加进代理名单

### ISSUE THREAD

**Issue by cyandee** [qiuyuzhou/ShadowsocksX-NG#1237]
pac模式下那个网站不会被代理只能开全局，但是我不想开全局，因为还要上国内的网站，我的梯子有流量限制。怎么把那个网站加进pac代理的名单里？求助。

**Comment by ssnhd** [comment]
代理设置——编辑 PAC 用户自定义规则，把域名添加进去。
举例：让 github 走代理，那么将 ||github.com^ 输入进去，然后重启即可。

**Comment by cyandee** [comment]
> 代理设置——编辑 PAC 用户自定义规则，把域名添加进去。
> 举例：让 github 走代理，那么将 ||github.com^ 输入进去，然后重启即可。
