### ISSUE TITLE
稳定靠谱，支持Trojan：https://portal.shadowsocks.nz/aff.php?aff=34033

### ISSUE THREAD

**Issue by JinPengCN** [qiuyuzhou/ShadowsocksX-NG#1242]
https://portal.shadowsocks.nl/aff.php?aff=34033

**Comment by cnsilvan** [comment]
> https://portal.shadowsocks.nl/aff.php?aff=34033

优惠码呢

**Comment by KaiboFu** [comment]
买了一个最便宜的 然后现在也用不了了

**Comment by JinPengCN** [comment]
> 买了一个最便宜的 然后现在也用不了了

每个服务器都切换试下，我的一直可用

**Comment by kkblock** [comment]
谁有优惠码

**Comment by SNGDude** [comment]
不点广告

**Comment by Alexander0211** [comment]
请问转成Trojan后还能再转后SS吗？
为什么转了Trojan后流量还变多了？是1比1转还是怎么回事？一直不敢点

**Comment by lbx6z** [comment]
有人知道这个网址现在被迁到哪儿了吗？
翻不了了又

**Comment by unlimitbladeworks** [comment]
> 谁有优惠码

https://portal.shadowsocks.au/aff.php?aff=36533

**Comment by chen1026241686** [comment]
> 

https://portal.shadowsocks.nz/aff.php?aff=57338

**Comment by zuoxiaolei** [comment]
https://portal.shadowsocks.nz/aff.php?aff=39205

**Comment by wangwt** [comment]
最新 [https://portal.shadowsocks.au](https://portal.shadowsocks.au/aff.php?aff=24693)

**Comment by wangwt** [comment]
最新 [https://portal.shadowsocks.au](https://portal.shadowsocks.au/aff.php?aff=24693)

**Comment by unlimitbladeworks** [comment]
2023年01月11日23:22:26 更新，最新地址：https://portal.shadowsocks.nz/aff.php?aff=36533

**Comment by linxid** [comment]
现在都已经挂掉了？

**Comment by tcluzhe** [comment]
> 
好了，需要改一下端口 443变成了465 应该，你登录客户中心看一下
https://portal.shadowsocks.au/

**Comment by NewBee466** [comment]
中国地区好像不能注册goolge账号
