### ISSUE TITLE
装了一下yangfeicheung / Shadowsocks-X后电脑无法访问谷歌了，求大神指点

### ISSUE THREAD

**Issue by Aaron-the-coder** [qiuyuzhou/ShadowsocksX-NG#1248]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**Diagnoisis file:**

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by arayinfree** [comment]
install old version 1.9.2

**Comment by Aaron-the-coder** [comment]
可以了谢谢,是服务器的问题




| |
Dale
|
|
邮箱：15650768800@163.com
|

Signature is customized by Netease Mail Master

在2020年02月03日 17:11，邓剑锐 写道：

install old version 1.9.2
