### ISSUE TITLE
shadowsocks服务节点无法翻墙了

### ISSUE THREAD

**Issue by ossaw** [qiuyuzhou/ShadowsocksX-NG#1260]
请问大佬们这几天是敏感时期吗? 今天我购买的服务节点无论是在手机上还是mac都失效了?  向官网反馈也没有得到回答

**Comment by lijia0514** [comment]
同求同求，我的也是能够打开但是所有网站都连接不了，google，youtube....求大咖回复。

**Comment by jzpy2myth** [comment]
+1

**Comment by cailfbit** [comment]
Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答

**Comment by cailfbit** [comment]
> Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答

修改服务器端口后可以用了

**Comment by Mickyn** [comment]
前天晚上还能用，现在我的所有设备都无法使用

**Comment by Mickyn** [comment]
> > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> 
> 修改服务器端口后可以用了

我的还无法使用

**Comment by cailfbit** [comment]
> > > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> > 
> > 
> > 修改服务器端口后可以用了
> 
> 我的还无法使用

定位是服务器问题了吗？

**Comment by Mickyn** [comment]
> > > > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> > > 
> > > 
> > > 修改服务器端口后可以用了
> > 
> > 
> > 我的还无法使用
> 
> 定位是服务器问题了吗？

所有服务器都无法使用了，前天晚上Japan1突然可以使用，昨天到今天均无法使用了

**Comment by ossaw** [comment]
都不好使了, 那应该是服务器节点的问题啊, 官网还没有恢复我

**Comment by y-bai** [comment]
都连不上了。。。服务器的问题。MAC和IPHONE都连不上了。。

**Comment by cailfbit** [comment]
> > > > > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> > > > 
> > > > 
> > > > 修改服务器端口后可以用了
> > > 
> > > 
> > > 我的还无法使用
> > 
> > 
> > 定位是服务器问题了吗？
> 
> 所有服务器都无法使用了，前天晚上Japan1突然可以使用，昨天到今天均无法使用了

我的也不行了，创建好不到1小时就不能用了，但修改服务器端口还能用，推测是封了端口，IP没封。修改端口每次坚持不过一天。

**Comment by ossaw** [comment]
> > > > > > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> > > > > 
> > > > > 
> > > > > 修改服务器端口后可以用了
> > > > 
> > > > 
> > > > 我的还无法使用
> > > 
> > > 
> > > 定位是服务器问题了吗？
> > 
> > 
> > 所有服务器都无法使用了，前天晚上Japan1突然可以使用，昨天到今天均无法使用了
> 
> 我的也不行了，创建好不到1小时就不能用了，但修改服务器端口还能用，推测是封了端口，IP没封。修改端口每次坚持不过一天。

请问修改端口是修改到固定的端口吗? 我修改了任意端口值还是不好使, 谢谢

**Comment by cailfbit** [comment]
> > > > > > > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> > > > > > 
> > > > > > 
> > > > > > 修改服务器端口后可以用了
> > > > > 
> > > > > 
> > > > > 我的还无法使用
> > > > 
> > > > 
> > > > 定位是服务器问题了吗？
> > > 
> > > 
> > > 所有服务器都无法使用了，前天晚上Japan1突然可以使用，昨天到今天均无法使用了
> > 
> > 
> > 我的也不行了，创建好不到1小时就不能用了，但修改服务器端口还能用，推测是封了端口，IP没封。修改端口每次坚持不过一天。
> 
> 请问修改端口是修改到固定的端口吗? 我修改了任意端口值还是不好使, 谢谢

修改固定端口。建议自己打一个Trojan或者买个tz比较好，稳定，折腾起来太麻烦了

**Comment by liaozd** [comment]
所有节点无法ping通，这次索性直接封锁IP了

**Comment by jhbxyz** [comment]
> 所有节点无法ping通，这次索性直接封锁IP了

是封了吗？现在无法使用啊

**Comment by yangyiRunning** [comment]
之前就一直断断续续的，基本上只有jp3和de1是好的，但是从昨天开始就彻底不行了，外网都上不去。ss官网至今也没有发布公告，求尽速解决啊~

**Comment by beiyehou** [comment]
同求

**Comment by y-bai** [comment]
我的是Mac，我清了一下DNS缓存就可以了。
[How To Clear Your DNS Cache](https://documentation.cpanel.net/display/CKB/How+To+Clear+Your+DNS+Cache)

**Comment by sunnibfgi** [comment]
> 我的是Mac，我清了一下DNS缓存就可以了。
> [How To Clear Your DNS Cache](https://documentation.cpanel.net/display/CKB/How+To+Clear+Your+DNS+Cache)

然而并没有什么用

**Comment by shuhan-v** [comment]
我前天的工单回复了，工作人员说是因为最近特殊时期，很多节点无法使用。

**Comment by lrhddzyj** [comment]
> 我前天的工单回复了，工作人员说是因为最近特殊时期，很多节点无法使用。

没有说大概什么时候能解封吗

**Comment by fanlinhu** [comment]
> Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答

我的弄好5分钟就不能用了

**Comment by shuhan-v** [comment]
> > 我前天的工单回复了，工作人员说是因为最近特殊时期，很多节点无法使用。
> 
> 没有说大概什么时候能解封吗
没说，下面是回复原文：
您好
由于最近是特殊时期，我们的服务器大量不可用 但是我们提供了新的协议您可以尝试切换

您如果愿意切换 请新建一个工单 标题为：申请切换为Trojan节点
因为切换是手工操作的，请注意如果您直接回复本工单答复可能会比较缓慢
由此带来的不便我们深表歉意

设置方法请参考： https://portal.shadowsocks.nl/knowledgebase/151/

请阅读下面的内容：
1. 目前 Trojan 服务的设置说明支持 Windows / Android / iOS(您需要已安装最新版 Shadowrocket / Pharos Pro 客户端)
2. 目前 Windows 目前暂不提供图形客户端，使用前需要先安装必须组件 vc_redist.x64.exe(点击前往微软官方下载)
3. 我们正在为您准备全新的客户端，请您等待我们的更新
4. Windows 使用前请完成对 Chrome / Firefox 的 SwitchOmega 扩展设置

Chrome 设置教程
Firefox 设置教程

**Comment by shuhan-v** [comment]
> > Mac OS 10.15.3 安装完用了一天之后就不能用了，本地客户端修改端口没用，求解答
> 
> 我的弄好5分钟就不能用了

今天早上能短暂上一会儿，就又不行了

**Comment by fanlinhu** [comment]
> 今天早上能短暂上一会儿，就又不行了

估计是现在疫情，国家在长城防火墙做了手脚了

**Comment by zhuojianhai** [comment]
一到关键时刻就出不去，恶心

**Comment by llwinner** [comment]
> 4. Windows 使用前请完成对 Chrome / Firefox 的 SwitchOmega 扩展设置
> 
> Chrome 设置教程
> Firefox 设置教程

你把这条回复删掉把，地址都暴露了。还嫌被封的不够吗？

**Comment by llwinner** [comment]
请不要在任何中国大陆的社交平台，如 QQ、微博、微信、百度贴吧等询问、发布、讨论任何相关的任何信息。感谢您的配合。

**Comment by shuhan-v** [comment]
谢谢提醒，我已经删除相关信息了。
