### ISSUE TITLE
Shadowsocks VPN does not work on my phone and my MAC laptop

### ISSUE THREAD

**Issue by NieYao1654** [qiuyuzhou/ShadowsocksX-NG#1261]
**Describe the bug**
Recently my shadowsocks VPN cannot work. All the address I have tried already but the result is the same. There is a few time that I can connect successfully, however, it quickly disable again.

**To Reproduce**
I have check my network and tried to reopen the app again and again. However it does not work.

**Expected behavior**
I do really hope the issue can be solved and my VPN can work stablely again.

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - macOS High Sierra 10.13.3

 - 1.6.1(1)

**Comment by hubery3721** [comment]
me too, my ShadowsocksX-NG version 1.9.4

**Comment by gydhy8** [comment]
me too, my ShadowsocksX-NG version 1.9.4 too, i used forgeground command run on my server:
ssserver -c /etc/shadowsocks.json start
and terminal display the shadowsocks started successfully, but when i access www.google.com with my chrome, nothing print out.

**Comment by llwinner** [comment]
就这么暴露服务器地址，就算能上也给你屏蔽了，就是因为总有这样的人，才导致经常被封，自己这么暴露地址被封是活该，但是连累其他人也上不，这样好吗？智商都哪儿去了？

**Comment by llwinner** [comment]
不知道把服务器打码？

**Comment by NieYao1654** [comment]
??
