### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by jaan-hou** [qiuyuzhou/ShadowsocksX-NG#1272]
memory leak 
![image](https://user-images.githubusercontent.com/11814908/75315351-83a59c80-589d-11ea-9d3c-740533b4d25b.png)

**Comment by jaan-hou** [comment]
software Version 1.4.7 (1)

os version : catalina 10.15.3

**Comment by qiuyuzhou** [comment]
The latest version is v1.9.4
The 1.4.7 won't be maintained.
