### ISSUE TITLE
导入url功能有问题

### ISSUE THREAD

**Issue by arthur-wxy** [qiuyuzhou/ShadowsocksX-NG#1280]
**Describe the bug**

*version* 1.9.4 
*macOS* 10.15.1
**To Reproduce**
Steps to reproduce the behavior
1.导入URLs-直接提示如图

P.S.url没有问题，同样的url在iPhone上可以使用

*麻烦大佬看下问题*

**Screenshots**
<img width="1440" alt="Screen Shot 2020-03-08 at 19 49 07" src="https://user-images.githubusercontent.com/39916187/76162200-31eef300-6176-11ea-99b4-5125502aea5e.png">

**Comment by qiuyuzhou** [comment]
导入url指的是scheme 是ss://开头的url。这个https的可能是服务商自己搞的远程配置，未标准化。请咨询你的服务提供商。

**Comment by arthur-wxy** [comment]
好的 谢谢
