### ISSUE TITLE
ShadowsocksX-NG 1.9.4 cannot work with latest kcptun server?

### ISSUE THREAD

**Issue by dna2github** [qiuyuzhou/ShadowsocksX-NG#1294]
**Describe the bug**
fill server and kcp info, then `ps -ef | grep kcp` and `ps -ef | grep ss-local`

it shows that `kcptun` run correctly with `-r <target_server>:<port> -l 127.0.0.1:<random_local_port> --key <key>`

the `ss-local` starts with generated config: `/Users/<name>/Library/Application Support/ShadowsocksX-NG/ss-local-config.json` i think it is correct;

only difference is that:

i uses kcp server 20200201 and 1.9.4 uses kcp client 20190905; some options like conn, autoexpire, scavengettl, ... may be changed in new version.

when i did: `curl --socks5 127.0.0.1:1086 https://www.google.com`; it fails after a long time (probably timeout).

does it means i MUST set up corresponding kcp server aligned with ShadowsocksX-NG kcp client?

my server config like this:
`ss-server 127.0.0.1:port1` -> `kcp-server 0.0.0.0:port2`

it works if i do:
`kcp-client -r <kcp-server>:port2 -l 127.0.0.1:port3` <- `ss-local -s 127.0.0.1 -p port3 -l 1086` <- `curl --socks5 127.0.0.1:1086 https://www.google.com`

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: MacOSX 10.15
 - Version 1.9.4

**Diagnoisis file:**

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by zyt1217** [comment]
Same problem for a long time.
