### ISSUE TITLE
各种订阅都正常，用其他客户端可以连接。

### ISSUE THREAD

**Issue by elvinzou** [qiuyuzhou/ShadowsocksX-NG#1299]
添加服务器地址正常，可以订阅，但是无法打开网页，上不了谷歌之类的外网，求解。

**Comment by masonincn** [comment]
* 和你一样，订阅正常，测速正常就是连不上外网；
* 使用 ShadowsocksX-NG-R8 也不行。
* 改了端口也无效。

**Comment by Codewyf-top** [comment]
同样的问题，依旧没有解决，有人有解决办法吗

**Comment by haiya512** [comment]
我也碰到了这个问题，上不了网
