### ISSUE TITLE
Wiki: bad uninstall shell script

### ISSUE THREAD

**Issue by h4x3rotab** [qiuyuzhou/ShadowsocksX-NG#1300]
On the wiki page, The path in last line of the uninstall shell script should be quoted.
<https://github.com/shadowsocks/ShadowsocksX-NG/wiki/FAQ#2-how-to-uninstall-shadowsocksx-ng>

The line:
```shell
sudo rm -rf /Library/Application Support/ShadowsocksX-NG/
```

should be changed to:
```shell
sudo rm -rf '/Library/Application Support/ShadowsocksX-NG/'
```

**Comment by qiuyuzhou** [comment]
Thanks. I have fixed it.
