### ISSUE TITLE
Not found valid QRcode of shadowsocks profile

### ISSUE THREAD

**Issue by doublelam** [qiuyuzhou/ShadowsocksX-NG#1316]
**Describe the bug**
open a QRcode on the screen and click scan qrcode from screen, would meet this error

**Screenshots**
![image](https://user-images.githubusercontent.com/12025501/82728660-75dca780-9d24-11ea-9c76-8fd50c7b6fc2.png)

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [macOS Catalina 10.15.4]
 - Version [1.9.4]

**Comment by doublelam** [comment]
是图片问题

**Comment by hoyangtsai** [comment]
I had the same issue. I used a QRcode image from the iOS shadowrocket export image.
