### ISSUE TITLE
应用打开后没有任何UI

### ISSUE THREAD

**Issue by HyphyPan** [qiuyuzhou/ShadowsocksX-NG#1321]
下载release版本后，打开app，没有任何界面出现，但是进程是开着的。是什么原因呢？是我使用方式不对吗？如果是的话，那我该怎么使用？

**Comment by HyphyPan** [comment]
误会了误会了。。。尴尬

**Comment by pingqunnayang** [comment]
> 误会了误会了。。。尴尬

这么解决的，M1 PRO出现类似问题，重启后可以出现，过一段时间自动消失了
