### ISSUE TITLE
Pods should NOT be committed.

### ISSUE THREAD

**Issue by yikerman** [qiuyuzhou/ShadowsocksX-NG#1333]
As [this post](https://stackoverflow.com/a/45587364) says.

**Comment by xinpingwang** [comment]
Why you ignore the most [most voted answer](https://stackoverflow.com/a/45587355)? As the this answer says (also documented in [CocoaPods official guides](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control)), both keep or ignore pods file has it's benefits. And the CocoaPod recommends keeping the Pods directory under source control, but still give decision to developers.

> Whether or not you check in your Pods folder is up to you, as workflows vary from project to project. **We recommend that you keep the Pods directory under source control**, and don't add it to your .gitignore. But ultimately this decision is up to you.

**Comment by yikerman** [comment]
### The reference of [the post](https://stackoverflow.com/a/45587364) just shows which to ignore.

In this situation:
- > the project can immediately build and run

That's true. But most apple devs have CocoaPod.

- > The Pod artifacts (code/libraries) are always available

There's no such worry, as those libs are all maintained actively. (Except BRLOptionParser, but [its author](https://github.com/stephencelis) is still alive.)

- > There won't be any conflicts to deal with when performing source control operations

That's what I'm worried about.

- > Technically there is no guarantee that running pod install will fetch and recreate identical artifacts when not using a commit SHA in the Podfile.

As long as there are no breaking changes between minor version numbers (If higher versions are downloaded accidentally), higher versions work even better, without breaking anything. Also, there are checksums in the lock file:

https://github.com/shadowsocks/ShadowsocksX-NG/blob/dd6149e3f253e22928d7bf8e54dfec798edaded5/Podfile.lock#L29
