### ISSUE TITLE
同一个服务器，用ShadowsocksX-NG-R8可以正常使用，用ShadowsocksX-NG不行

### ISSUE THREAD

**Issue by kinaito** [qiuyuzhou/ShadowsocksX-NG#1335]
由于是同一个服务器，不存在服务器的原因，服务器的其他服务也正常运作中。

本来想更新ShadowsocksX-NG-R8，但是现在没人维护了，下载了ShadowsocksX-NG.1.9.4
启动后，读取了我的本地配置，连接同一个服务器：无连接信息

关闭后，使用 ShadowsocksX-NG-R8，正常
查看本地日志，没有报错

这是为什么？需要我提供哪部分的日志才能帮助解决这个问题

加密：chacha20-ietf
协议：aes128_md5
混淆：tls1.2_ticket_auth
有使用混淆参数

**Comment by paradiseduo** [comment]
maybe you need [ShadowsocksX-NG-R8](https://github.com/paradiseduo/ShadowsocksX-NG-R8)

**Comment by chiseller** [comment]
ShadowsocksX-NG.不支持ssr，ShadowsocksX-NG-R8支持ssr，你这很明显用的ssr
