### ISSUE TITLE
The latest macOS big sur beta software cannot be displayed in the menu bar

### ISSUE THREAD

**Issue by p5ydn0** [qiuyuzhou/ShadowsocksX-NG#1337]
**Describe the bug**

The latest macOS big sur beta software cannot be displayed in the menu bar.

There is one more problem, but I’m not sure if it’s the software’s problem, that is, I didn’t find the related process of the software in the activity monitor software, but my computer can indeed implement `fq` normally (I did not use any other similar tools) .

**To Reproduce**

Start the software.

**Expected behavior**

After the software is started, the software icon can be found in the menu bar normally, and then the normal status display and settings can be performed by clicking the icon.

**Screenshots**

Unrealizable.

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: macOS Big Sur 11.0 Beta
- Version：Unavailable; most likely the latest version.

**Additional context**

Attempted to restart the computer; the problem persists after the restart.

Thanks.

**Comment by yikerman** [comment]
@p5ydn0 Cannot repro. Maybe it's an OS bug.

**Comment by p5ydn0** [comment]
I found out that the reason for this error was caused by an error in the menu management software I used under the new system. It has nothing to do with ShadowsocksX-NG.

Sorry about that.
