### ISSUE TITLE
作者在墙内，难道不会被网警请去喝茶么？

### ISSUE THREAD

**Issue by jamesiter** [qiuyuzhou/ShadowsocksX-NG#1339]
![image](https://user-images.githubusercontent.com/2541839/90326080-8bc1d780-dfb6-11ea-9fbc-4195c7d20e42.png)

**Comment by xiaoyu2006** [comment]
这不是重点

**Comment by nstylec** [comment]
这不是很久没更新了么……

**Comment by zhangyh233** [comment]
那你还截个图出来，真是恶心至极素质极差- -#

**Comment by Hanice404** [comment]
你用菜刀杀人，难道要去抓卖刀的么？

**Comment by jamesiter** [comment]
那要看在哪呢。如果是朝鲜、伊朗、古巴，还真是这样呢。
