### ISSUE TITLE
Don't work on MacOS 10.15.7

### ISSUE THREAD

**Issue by st9st9** [qiuyuzhou/ShadowsocksX-NG#1350]
Nothing changes when connecting to the server. Only in Safari writes "Safari cannot open this page." Changed proxy in browser settings. The servers are obviously working, I checked them on Android.
Tried PAC, Manual and Global.

**Comment by st9st9** [comment]
And some servers are not added, but they are quietly added to Android.
<img width="698" alt="Снимок экрана 2020-10-25 в 12 16 12" src="https://user-images.githubusercontent.com/73422209/97103174-e5800580-16bb-11eb-98ff-0bf2d0d2aca1.png">

Example: _"ss://YWVzLTI1Ni1jZmI6ZUlXMERuazY5NDU0ZTZuU3d1c3B2OURtUzIwMXRRMERAMTM5LjE2Mi4xNS40NTo4MDk3#翻墙党127.11新加坡"_

**Comment by yikerman** [comment]
> Example: "ss://YWVzLTI1Ni1jZmI6ZUlXMERuazY5NDU0ZTZuU3d1c3B2OURtUzIwMXRRMERAMTM5LjE2Mi4xNS40NTo4MDk3#翻墙党127.11新加坡"

@soso4ek228 Try not to include the `#...` part.
Try `ss://YWVzLTI1Ni1jZmI6ZUlXMERuazY5NDU0ZTZuU3d1c3B2OURtUzIwMXRRMERAMTM5LjE2Mi4xNS40NTo4MDk3`.

**Comment by st9st9** [comment]
Thanks. It all worked!
