### ISSUE TITLE
服务器全部failed，怎么回事？

### ISSUE THREAD

**Issue by GjyJason** [qiuyuzhou/ShadowsocksX-NG#1356]

**Comment by zwc456baby** [comment]
在这里说明一下临时解决方案。如果你用的 ss，使用了 v2ray-plugin 插件

那么你的现象和我是一样的，原因是 v2ray-plugin 在最新 maxOs 系统上无法运行了。。

可以用秋水的最新版本。

https://github.com/teddysun/v2ray-plugin

进入上方项目地址，在 release 页面下载新的 v2ray-plugin ，替换原有目录下的 v2ray-plugin 后

即可，亲测

**Comment by jacklaoz** [comment]
服务器不能用 跟这个客户端有毛关系  自己搭梯子不香么
