### ISSUE TITLE
FR: Port the project to Apple Silicon

### ISSUE THREAD

**Issue by XIAZY** [qiuyuzhou/ShadowsocksX-NG#1358]
Apple Silicon Macs are out for a while. This app runs fine under Rosetta, however, we should still port it to Apple Silicon for better efficiency.

I am not sure if maintainers have a plan to port it to Apple Silicon. If not, I can submit a PR for it.

**Comment by yikerman** [comment]
> I am not sure if maintainers have a plan to port it to Apple Silicon. If not, I can submit a PR for it.

@XIAZY The real question is that ssX-NG embedded an x86 binary shadowsocks-libev port.

Also see #1332.

**Comment by XIAZY** [comment]
Gotcha. I will close this issue and use #1332 as a master tracker.
