### ISSUE TITLE
The MAC's latest system, Big Sur, is not working

### ISSUE THREAD

**Issue by skCNA** [qiuyuzhou/ShadowsocksX-NG#1359]
Unable to over the wall after system update
I don't know if that's the case with you

**Comment by Ruihang** [comment]
@skCNA 有什么解决方法吗

**Comment by wanghaifeng** [comment]
> @skCNA 有什么解决方法吗

https://github.com/shadowsocks/ShadowsocksX-NG/issues/1369#issuecomment-787420087

**Comment by skCNA** [comment]
我的问题是V2ray插件因为big sur导致不可用，在网上找找，有人提供了重新编译后的包，应该是在评论里，下载替换老的就好了



---Original---

**Comment by dddreee** [comment]
> > @skCNA 有什么解决方法吗
> 
> [#1369 (comment)](https://github.com/shadowsocks/ShadowsocksX-NG/issues/1369#issuecomment-787420087)

我尝试了下，没用。。
我直接把软件删了然后重启电脑，重新下载了个打开就能用了
