### ISSUE TITLE
“ss-local" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by qiluo** [qiuyuzhou/ShadowsocksX-NG#1362]
刚刚从1.4.x升级到1.9.4，但是打开后就显示“ss-local" cannot be opened because the developer cannot be verified，而且只能选择移动到回收站或者取消，没有信任选项。请问如何处理

**Comment by yikerman** [comment]
@qiluo See https://support.apple.com/en-us/HT202491.

**Comment by qiluo** [comment]
> @qiluo See https://support.apple.com/en-us/HT202491.

试过了，这种方式不行呢，以前application都是这种方式解决的，现在这个ss-local是个命令行binary

**Comment by yikerman** [comment]
@qiluo Try https://github.com/hashicorp/terraform/issues/23033#issuecomment-540262070.

**Comment by qiluo** [comment]
> @qiluo Try [hashicorp/terraform#23033 (comment)](https://github.com/hashicorp/terraform/issues/23033#issuecomment-540262070).

thanks
