### ISSUE TITLE
Big Sur: Proxifier v3 与 NG 不能同时工作

### ISSUE THREAD

**Issue by nonovv** [qiuyuzhou/ShadowsocksX-NG#1364]
启动Proxifer，则NG代理失败。

OS Version:  Big Sur 11.1
Proxifier: v3.4
ShadowsocksX-NG: 1.9.4

**Comment by jijie85** [comment]
一模一样

**Comment by MrXCQ** [comment]
我bigsur  直接不能使用了 无法正常上网

**Comment by Wizr** [comment]
Proxifier的问题，他们网站有说明

**Comment by jijie85** [comment]
OK
之前用了他们一个降级的版本，能用了。
感谢。






------------------&nbsp;Original&nbsp;------------------

**Comment by nonovv** [comment]
Proxifier的问题，他们网站有说明
