### ISSUE TITLE
Support on Mac M1?

### ISSUE THREAD

**Issue by occamrazor1492** [qiuyuzhou/ShadowsocksX-NG#1370]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yikerman** [comment]
@occamrazor1492 Refer to my issue #1332.

**Comment by occamrazor1492** [comment]
> @occamrazor1492 Refer to my issue #1332.

As this is a redundant feature request, would close it.
