### ISSUE TITLE
关于软件的后续更新维护问题

### ISSUE THREAD

**Issue by vndi** [qiuyuzhou/ShadowsocksX-NG#1375]
您好，想问问您是否还有后续跟进维护该项目的意愿？

**Comment by yikerman** [comment]
It doesn’t seem to be very possible... :-/

**Comment by jack80342** [comment]
我在维护。https://github.com/jack80342/ShadowsocksX-NG-R

**Comment by Goodwu** [comment]
> 我在维护。https://github.com/jack80342/ShadowsocksX-NG-R

可惜我用shadowsock+kcptun，不用SSR

**Comment by vndi** [comment]
> https://github.com/jack80342/ShadowsocksX-NG-R

thanks for doing that
