### ISSUE TITLE
新买的m1 mac无法使用订阅，也无法连接服务器

### ISSUE THREAD

**Issue by RuoxuZhang** [qiuyuzhou/ShadowsocksX-NG#1380]
新买的m1 macbook pro，

1）使用订阅地址后点击手动更新没有反应，
2）连接自己搭的服务器也不能科学上网，
3）使用小猴子客户端连接ssr和v2ray节点也不能科学上网，

上述这些方式用我的windows是可以上网的，但新买的macbook不行，请问是什么原因？

**Comment by Kerinlin** [comment]
我也是m1 mp,这一版NG有问题，你使用NG-R8版本的

**Comment by NookyPOP** [comment]
> 我也是m1 mp,这一版NG有问题，你使用NG-R8版本的
您好，你是怎么配置的，不知道是不是我配置的问题，就是不能上外网；使用clash for mac可以上外网

**Comment by NookyPOP** [comment]
@Kerinlin

**Comment by dirtydamn1** [comment]
请问解决了吗，m1pro有坑啊

**Comment by Kerinlin** [comment]
> 

还是使用clash吧，有问题

**Comment by dirtydamn1** [comment]
> > 
> 
> 还是使用clash吧，有问题

好的，我试试
