### ISSUE TITLE
Mac M1 - not working

### ISSUE THREAD

**Issue by GPopkov** [qiuyuzhou/ShadowsocksX-NG#1381]
**Describe the bug**
Problem on Mac and MacBook M1

**To Reproduce**
Clean install

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 11.4 Big Sur 
 - iMac (Intel) and MacBook Air M1
- Shadowsocksx-NG version 1.9.4

I have Centos 7 server with Shadowsoks/v2ray installation working good with Windows clients (scr1)
![scr1](https://user-images.githubusercontent.com/86493086/123476254-1f1b5e80-d605-11eb-8503-60434c724eeb.png)
, but I cannot enable client on iMac or MacBook M1 Big Sur (Shadowsocksx-NG clean install, all settings by default, server settings on scr2)
<img width="547" alt="scr2" src="https://user-images.githubusercontent.com/86493086/123476629-a5d03b80-d605-11eb-9fa3-d4cb60f5a92a.png">

It's my first installation Shadowsocks client on Mac, where can be my mistake?

**Comment by GPopkov** [comment]
Problem solved.
v2ray-plugin included in Mac OS client Shadowsocksx-NG 1.9.4 - isn't compatible with Mac OS 11 Big Sur
It's necessary to use v2ray version 4 or higher, https://github.com/v2ray/v2ray-core/releases
I test on v2ray 4.23.2, work fine.

**Comment by JackZhaoNB** [comment]
@GPopkov How to use v2ray version 4 ?
