### ISSUE TITLE
mac电脑按照步骤来的为什么还是打不开google

### ISSUE THREAD

**Issue by lixinyuyu** [qiuyuzhou/ShadowsocksX-NG#1385]
mac电脑
http://91tianlu.fashion/knowledgebase.php?action=displayarticle&id=3根据这个教程六部都走了
但是还是连接不上google是为什么呢？

**Comment by MoonCheung** [comment]
是mac的翻墙头疼问题

**Comment by lixinyuyu** [comment]
close
