### ISSUE TITLE
ShadowsocksX-NG.1.7.1 不支持macOs Monterey

### ISSUE THREAD

**Issue by ghost** [qiuyuzhou/ShadowsocksX-NG#1389]
升级macOs Monterey后，使用ShadowsocksX-NG.1.7.1无法翻墙，换成1.9.4也无法翻墙

**Comment by password36** [comment]
怎么解决的，我现在也是升级了Monterey后safari不能链接SS，但是chrome和终端是可以的。

**Comment by leaderliang** [comment]
Mac OS 12.0.1 monterey 确实不能使用

**Comment by password36** [comment]
> Mac OS 12.0.1 monterey 确实不能使用

我切换v2RayU客户端了，界面和原理和这个都一样，也支持服务器ss协议，应该就是设置网络路由有问题。
