### ISSUE TITLE
MacOS 12.0.1 无法正常使用

### ISSUE THREAD

**Issue by thtTNT** [qiuyuzhou/ShadowsocksX-NG#1393]
需在在网络设置中手动开启“自动发现代理”配置后才可以使用
<img width="624" alt="image" src="https://user-images.githubusercontent.com/17686312/140250443-14b54d74-41ee-415d-ac8e-3d34fe040a35.png">
一旦SS重启或者切换模式会导致配置会覆盖，需要重新开启

**Comment by fanlb** [comment]
👍👍👍👍👍
