### ISSUE TITLE
什么时间可以新出一个版本呀，适配M1及更新v2ray！！！！

### ISSUE THREAD

**Issue by ericellis7** [qiuyuzhou/ShadowsocksX-NG#1395]
求更新，求适配！求发布新版本！~！！！！！

**Comment by yikerman** [comment]
@EricMzky 我在做适配：https://github.com/ssx-ng/ShadowsocksX-NG

但最近学业繁忙没时间更新

**Comment by ericellis7** [comment]
> @EricMzky 我在做适配：https://github.com/ssx-ng/ShadowsocksX-NG
> 
> 
> 
> 但最近学业繁忙没时间更新

跪求更新release发布版本！

**Comment by KyleXie** [comment]
我 pull 了最新的 develop 分支的代码，自己编译了一个版本，测了下在 M1 上是可以用的。

**Comment by xiangbohua** [comment]
trojan 其实也是迫切需要

**Comment by ericellis7** [comment]
> 我 pull 了最新的 develop 分支的代码，自己编译了一个版本，测了下在 M1 上是可以用的。

支持v2ray-plugin这个插件嘛？

**Comment by ericellis7** [comment]
> 我 pull 了最新的 develop 分支的代码，自己编译了一个版本，测了下在 M1 上是可以用的。

有链接吗？

**Comment by KyleXie** [comment]
> > 我 pull 了最新的 develop 分支的代码，自己编译了一个版本，测了下在 M1 上是可以用的。
> 
> 支持v2ray-plugin这个插件嘛？

有 v2ray，我也是用的 v2ray 插件

**Comment by ericellis7** [comment]
> > > 我 pull 了最新的 develop 分支的代码，自己编译了一个版本，测了下在 M1 上是可以用的。
> 
> > 
> 
> > 支持v2ray-plugin这个插件嘛？
> 
> 
> 
> 有 v2ray，我也是用的 v2ray 插件

可以给链接地址嘛？下载一个谢谢

**Comment by KyleXie** [comment]
@EricMzk 你试试能不能用，这个我在自己电脑上编译的
[ShadowsocksX-NG.app.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/7611705/ShadowsocksX-NG.app.zip)
y

**Comment by zhanggang807** [comment]
> @EricMzk 你试试能不能用，这个我在自己电脑上编译的 [ShadowsocksX-NG.app.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/7611705/ShadowsocksX-NG.app.zip) y

m1 big sur可用

**Comment by sophauer** [comment]
> @EricMzk 你试试能不能用，这个我在自己电脑上编译的 [ShadowsocksX-NG.app.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/7611705/ShadowsocksX-NG.app.zip) y

用xchacha20-ietf-poly1305显示不支持的组件,用chacha20-ietf-poly1305正常

**Comment by nealgavin** [comment]
这个最新的版本，为啥在mac 12.1打不开?双击没反应，界面也不出，没看到报错
