### ISSUE TITLE
mac m1 已经安装了 rosetta2

### ISSUE THREAD

**Issue by numbernumberone** [qiuyuzhou/ShadowsocksX-NG#1397]
![image](https://user-images.githubusercontent.com/17960477/142755657-b7fc2483-3850-423c-bab3-7e74d73c7e8c.png)
开启shadowsocks 无法使用google.com。

机器是mac mini m1 

系统是  12.0.1

**Comment by zengdd-pro** [comment]
不会啊，我系统也是12.0.1的。
我刚下载的版本ShadowsocksX-NG.1.9.4.zip。解压后直接就运行了，正确配置好服务器就可以了。
提前安装好Rosetta
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
