### ISSUE TITLE
missing code signature in version 1.10.0?

### ISSUE THREAD

**Issue by suschizu** [qiuyuzhou/ShadowsocksX-NG#1438]
**Describe the bug**
The code signature has changed between 1.9.4 and 1.10.0:

EXPECTED:
Shenzhen Shun Dao Chu Xing Technology Co., Ltd. (RJX3H8KBAF) 
but FOUND

**To Reproduce**
codesign -dv --verbose=4 /Path/To/Application.app

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 12.6
 - Version1.10.0

**Comment by lkebin** [comment]
v1.10.0 released by Github Actions, it doesn't have Apple certificate for signature, but the released binary file could be trusted by anyone.

Check Github workflows file and Makefile to view the build process.

**Comment by yakovmanshin** [comment]
Would it be possible to add a workflow step to send the binary to the notarization service, or, even better, upload the build to the Mac App Store?

In my opinion, the security alerts look pretty frightening and significantly limit the project’s reach.
