### ISSUE TITLE
HTTP Proxy doesn't work

### ISSUE THREAD

**Issue by danny-su** [qiuyuzhou/ShadowsocksX-NG#1441]
![image](https://user-images.githubusercontent.com/12178855/213165701-12a9655a-46ba-49cd-8490-19a868f7dfc2.png)
![image](https://user-images.githubusercontent.com/12178855/213165788-5b0289c3-6b5e-4f92-a09e-a58cd6b3dc2f.png)
![image](https://user-images.githubusercontent.com/12178855/213165829-a35aefd8-3f32-4567-a4e2-31b1244a7af6.png)

**Comment by raidenxu** [comment]
me too

**Comment by lkebin** [comment]
Could you check socks5 listen port value in `Advanced` tab? For your case, your possible using same port for both socks5 and http protocol, and http proxy service start in error

**Comment by danny-su** [comment]
> Could you check socks5 listen port value in `Advanced` tab? For your case, your possible using same port for both socks5 and http protocol, and http proxy service start in error

I used different ports for socks5 and http, and now the http proxy agent (ss-local) started, I can use http proxy. just delay?

**Comment by hiwanz** [comment]
didnt work

**Comment by nangcr** [comment]
Try to start privoxy manually.

```
cd ~/Library/Application\ Support/ShadowsocksX-NG
./privoxy privoxy.config
```

**Comment by wyfang** [comment]
> 

Worked！How？？
And what went wrong? How to fix it? Instead of running it manually.

**Comment by nangcr** [comment]
> > 
> 
> Worked！How？？ And what went wrong? How to fix it? Instead of running it manually.

Architecture change to arm at version 1.10 and cause this bug. Wait for the bug fix.

**Comment by wyfang** [comment]
> 

OK

**Comment by xdxiaodong** [comment]
+1

**Comment by internationalJoke** [comment]
> ./privoxy privoxy.config

./privoxy: command not found
I met this problem when I tried to execute this command.

**Comment by bdyebd** [comment]
I hit the same issue and find actually I have `~/Library/Application\ Support/ShadowsocksX-NG/privoxy` but the plist actually calling `~/Library/Application\ Support/ShadowsocksX-NG/privoxy/**privoxy**` . If you hit same issue, just create a directory `privoxy` and move the binary `privoxy` into it. Should fix all such issue.

**Comment by bdyebd** [comment]
It's an upgrade issue from 1.9.4 to 1.10.0+. Just remove `~/Library/Application\ Support/ShadowsocksX-NG/privoxy` also works because the app copy this folder again if it not exists. The origin binary there blocks copy of that folder.

**Comment by hiwanz** [comment]
I Just remove `~/Library/Application\ Support/ShadowsocksX-NG/*` and it seems good.
> It's an upgrade issue from 1.9.4 to 1.10.0+. Just remove `~/Library/Application\ Support/ShadowsocksX-NG/privoxy` also works because the app copy this folder again if it not exists. The origin binary there blocks copy of that folder.

**Comment by hiwanz** [comment]
I Just remove `~/Library/Application\ Support/ShadowsocksX-NG/*` and it seems good.
> It's an upgrade issue from 1.9.4 to 1.10.0+. Just remove `~/Library/Application\ Support/ShadowsocksX-NG/privoxy` also works because the app copy this folder again if it not exists. The origin binary there blocks copy of that folder.

**Comment by pnck** [comment]
still not fixed

**Comment by zplzpl** [comment]
<img width="284" alt="image" src="https://github.com/shadowsocks/ShadowsocksX-NG/assets/7931755/184b8bba-c7e7-4189-9ef4-0f2e24905c6a">

v1.9.4 has same issue.

**Comment by rainywinter** [comment]
> I hit the same issue and find actually I have `~/Library/Application\ Support/ShadowsocksX-NG/privoxy` but the plist actually calling `~/Library/Application\ Support/ShadowsocksX-NG/privoxy/**privoxy**` . If you hit same issue, just create a directory `privoxy` and move the binary `privoxy` into it. Should fix all such issue.

it works to me, thanks 

mac os 14.3 (23D56)
shadowsocks-ng v1.10.2 (1)

**Comment by lkebin** [comment]
> It's an upgrade issue from 1.9.4 to 1.10.0+. Just remove `~/Library/Application\ Support/ShadowsocksX-NG/privoxy` also works because the app copy this folder again if it not exists. The origin binary there blocks copy of that folder.

That's the way to resolve similar problem.
