### ISSUE TITLE
How to setup cloak?

### ISSUE THREAD

**Issue by hawshemi** [qiuyuzhou/ShadowsocksX-NG#1447]
Can I use shadowsocksX-NG alongside Cloak (on macOS)?
https://github.com/cbeuw/Cloak

**Comment by axce1** [comment]
same question

**Comment by Ali4code** [comment]
Same here,
I have shadowsocks cloak seever and android client + cloak ck client installed

I Want same with mac

**Comment by hawshemi** [comment]
I think the only way is to use ShadowRocket...
