### ISSUE TITLE
when started, the privoxy service did not start automatically

### ISSUE THREAD

**Issue by javyxu** [qiuyuzhou/ShadowsocksX-NG#1463]
**Describe the bug**
when started, the privoxy service did not start automatically

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version:  macOS Ventura 13.3
 - Version v1.10.2 

**Additional context**
I need to execute the command manually ` cd ~/Library/Application\ Support/ShadowsocksX-NG && ./privoxy privoxy.config`

**Comment by zkyle95** [comment]
This comment works to me. https://github.com/shadowsocks/ShadowsocksX-NG/issues/1441#issuecomment-1485064586

**Comment by lijunn** [comment]
I find the same bug , no button to start the privoxy,only start by command
