### ISSUE TITLE
Where is the configuration file？

### ISSUE THREAD

**Issue by xiatian12345** [qiuyuzhou/ShadowsocksX-NG#1473]
* I find all my compute ,i can't find the configuration file.*

* the path `/Applications/ShadowsocksX-NG.app/Contents/Resources` can not found*
* the path `~/.ShadowsocksX-NG` have nothing *
* the path `~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist` i found it,but i change the configuration file,my app is not effective. on the contrary i set my app configure the file is effect,so the file also not the really configuration file too.*

*The really configuration file is in db? Can you help me ?*

**Comment by Wizr** [comment]
`~/Library/Application Support/ShadowsocksX-NG`

**Comment by xiatian12345** [comment]
> `~/Library/Application Support/ShadowsocksX-NG`

It is also incorrect
