### ISSUE TITLE
Shadowsocks failed to work, SSL handshake -9806

### ISSUE THREAD

**Issue by CaulyKan** [qiuyuzhou/ShadowsocksX-NG#16]
Hello mr. qiu,

My shadowsocksX was working properly but this week it suddenly fail to work as well as shadowsocksX-NG. Proxy can't go through socks5 127.0.0.1:1080 (However ssh -D 1080 does). While trying to update gfw list in global proxy mode, it informs me with:

16/7/22 上午12:52:10.848 ShadowsocksX-NG[2491]: CFNetwork SSLHandshake failed (-9806)
16/7/22 上午12:52:10.849 ShadowsocksX-NG[2491]: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)

Any ideas?

Thank you very much!

**Comment by qiuyuzhou** [comment]
Have you updated your mac os to 10.11.6 this week?

**Comment by CaulyKan** [comment]
No, I'm at 10.11.5

**Comment by CaulyKan** [comment]
It seems that none of my mac, android and windows client is working now. Weird...

**Comment by qiuyuzhou** [comment]
The default listen port is 1086.
Check the listen port in the advance preferences dialog.
Listen on 127.0.0.1 instead of localhost.

Check ss-local.log, there should be something like:
```
2016-07-22 13:50:03 INFO: tcp port reuse enabled
2016-07-22 13:50:03 INFO: udprelay enabled
2016-07-22 13:50:03 INFO: udp port reuse enabled
2016-07-22 13:50:03 INFO: listening at 127.0.0.1:1086
```

**Comment by CaulyKan** [comment]
`2016-07-23 02:23:31 INFO: closed gracefully
2016-07-23 02:23:32 INFO: onetime authentication enabled
2016-07-23 02:23:32 INFO: initialize ciphers... rc4-md5
2016-07-23 02:23:32 INFO: tcp port reuse enabled
2016-07-23 02:23:32 INFO: listening at 127.0.0.1:1080
2016-07-23 02:23:33 INFO: connect to www.google.com:443
2016-07-23 02:23:33 INFO: connect to www.google.com:443
2016-07-23 02:23:34 INFO: connect to www.google.com:443`

Chrome still complains ERR_CONNECTION_CLOSED

**Comment by qiuyuzhou** [comment]
You use SwitchyOmega?
Have you set correct proxy protocol type in SwitchyOmega?

**Comment by CaulyKan** [comment]
Sure. Shadowsocks keeps working properly until previous week.

**Comment by qiuyuzhou** [comment]
Have you try to roboot system?

**Comment by CaulyKan** [comment]
That didn't help too.

**Comment by qiuyuzhou** [comment]
Have you try to set proxy in system settings, not  in SwitchyOmega?
There is only verbose mode of ss-local. It seem to you have enabled it.

**Comment by CaulyKan** [comment]
more infomation:

On server, ss-server has wrote shadowsocks.log like this:
`
WARNING  unsupported addrtype 19, maybe wrong password
ERROR    can not parse header when handling connection from XXXX
`

**Comment by CaulyKan** [comment]
I download the newest shadowsocks client from https://github.com/shadowsocks/shadowsocks/releases/tag/2.8.2, build and install it, then use the same config file from Shadowsocks-NG `sslocal -c ~/Library/Application\ Support/ShadowsocksX-NG/ss-local-config.json` , And everything goes well now.
Is there any difference between your ss-local and the one mentioned above?

**Comment by qiuyuzhou** [comment]
I see you have enabled OTA(onetime authentication). Are you sure your ss server support it?

**Comment by CaulyKan** [comment]
That's the problem. I shouldn't have check the OTA option.

Thank you very much for your support! 非常感谢～
