### ISSUE TITLE
可以尝试支持 SS-R

### ISSUE THREAD

**Issue by bazingaterry** [qiuyuzhou/ShadowsocksX-NG#17]
ShadowsocksR 有 [libev 版本](https://github.com/breakwa11/shadowsocks-libev)，也兼容原版的协议，希望这个功能可以提上日程。

**Comment by qinyuhang** [comment]
赞同，而且有人已经打包了 libev 版本的作为 GoAgentX 的插件，已有 Release，可否直接 Merge 进来？

**Comment by qiuyuzhou** [comment]
暂时没有计划。
欢迎fork后，自行开发。

**Comment by qiuyuzhou** [comment]
个人认为ssr改进方向是歪的，也从来没用过ssr。
