### ISSUE TITLE
工具栏显示网速

### ISSUE THREAD

**Issue by zarvin** [qiuyuzhou/ShadowsocksX-NG#19]
希望可以像 surge Mac 一样能在工具栏显示当前网络上传下载速度

**Comment by qiuyuzhou** [comment]
目前不会考虑。
因为是通过外部进程ss-local提供ss服务，shadowsocksX-NG本身只是一个GUI控制界面。
需要修改lib-ev版的ss-local提供统计信息输出。

**Comment by qiuyuzhou** [comment]
可以考虑改进libev的ss-local，记录统计信息，并且输出到一个指定文件中，每秒更新。然后GUI程序每秒读取。
目前没有时间，也不熟悉libev的代码。短期内不考虑。
欢迎其他人在libev中实现了的相应的功能。
