### ISSUE TITLE
突然只有在全局模式下才可以穿墙了

### ISSUE THREAD

**Issue by yongjun925** [qiuyuzhou/ShadowsocksX-NG#22]
前几天用着好好的，突然就不能愉快的使用的

**Comment by yongjun925** [comment]
自己捣鼓了半天，发现不能像原来一样使用http://127.0.0.1:1080了，换成socks 5协议正常使用了

**Comment by qiuyuzhou** [comment]
原版也不支持http代理的。
只是socks5代理缺省端口不一样，这是为了避免在同时安装原本和ng版时冲突。

原版是在内部开个web服务器通过http协议提供pac脚本的。
现在版本是直接使用指向文件URL(file:///Users/qiuyuzhou/.ShadowsocksX-NG/gfwlist.js)
