### ISSUE TITLE
没有~/Library/LaunchAgents文件夹启动故障

### ISSUE THREAD

**Issue by andres-lee** [qiuyuzhou/ShadowsocksX-NG#23]
hi~，你知道 [kcptun](https://github.com/xtaci/kcptun) 吗？  这两天我把你这个项目里的ss-local换成了kcptun，效果还是不错滴。 但是今天打好包拿到公司的mac mini上试了下，结果启动不了。 一查原来这台mac mini上没有LanuchAgents目录，导致启动脚本写入失败。
        因为我不是搞ios开发的，很多地方不熟悉，不知是否是我哪里没改对。。。

**Comment by qiuyuzhou** [comment]
知道kcp。
kcptun改用不同于tcp的流量控制策略，牺牲一定公平性，多发10%-@20%包以应对丢包的情况。
