### ISSUE TITLE
ShadowsocksX-NG启动时总是清空系统代理设置

### ISSUE THREAD

**Issue by yang-s-li** [qiuyuzhou/ShadowsocksX-NG#24]
> Add a manual mode which won't configure the system proxy settings

根据readme的说法，手动模式不会修改系统代理设置，但我反复测试发现，在「Shadowsocks：关闭」的情况下，只要SSX-NG启动，就会清空系统代理，不管是Pac自动模式、全局模式、手动模式，也不管「高级代理设置」的「自动设置」选项是否勾选，请确认是否是bug。

备注：
- ShadowsocksX不会出现这个问题。
- 我知道在「Shadowsocks：打开」的情况下，系统代理设置会被修改，但目前我并没有打开。

环境：
- Mac OS version: 10.11.6
- SSX-NG version: 1.1

**Comment by qiuyuzhou** [comment]
在proxy_conf_helper里加了判断，仅在当前配置是由ShadowsocksX-NG设置的情况下，才重置为空。

**Comment by yang-s-li** [comment]
多谢。

预计何时会打包成dmg供下载？

**Comment by qiuyuzhou** [comment]
已经打包了发布1.2版了
