### ISSUE TITLE
添加服务器里面的OTA是什么呢

### ISSUE THREAD

**Issue by mk87878** [qiuyuzhou/ShadowsocksX-NG#25]
添加服务器里面的OTA是什么呢

**Comment by qiuyuzhou** [comment]
OTA是One Time Auth的缩写。不是所有服务器都支持。
如果你不知道它是什么，就不用启用。

https://shadowsocks.org/en/spec/one-time-auth.html

**Comment by mk87878** [comment]
恩，知道了，谢谢解答，我服务器端的确不支持，，，，
