### ISSUE TITLE
请详细解释一下手动模式的工作方式

### ISSUE THREAD

**Issue by yang-s-li** [qiuyuzhou/ShadowsocksX-NG#27]
以下问题我不太明白：

- 手动模式只是为了「不更改系统代理」而存在吗？
- 在手动模式，流量是走「全局」还是「pac自动」代理？

**Comment by qiuyuzhou** [comment]
有用户希望手工配置代理（例如使用Chrome插件Proxy SwitchyOmega），不依靠ShadowsocksX-NG控制系统的代理配置。
手动模式，ss-local仍然在后台运行，只是不修改系统的代理配置，要使用ss需要用户自行在系统或浏览器里配置。
行为等同于原版ShadowsocksX的“关闭Shadowsocks”，现在版本的“关闭Shadowsocks”会停止ss-local运行。

**Comment by yang-s-li** [comment]
我现在默认就是「关闭Shadowsocks」，因为我在系统代理设置了Privoxy的监听端口，但与此同时我可以选择是「pac自动」还是「全局」代理：

![image](https://cloud.githubusercontent.com/assets/20695423/17403337/d75478d0-5a89-11e6-9665-fd2f92755113.png)

所以我想知道SSX-NG如何设置可以满足我的需求？

**Comment by qiuyuzhou** [comment]
- 「打开Shadowsocks」
- 手动模式
- privoxy指向ss的socks5的端口

**Comment by yang-s-li** [comment]
按照你的步骤操作之后，流量是走「pac自动」还是「全局」代理？

**Comment by qiuyuzhou** [comment]
完全跟「pac自动」还是「全局」没关系了。
ShadowsockX-NG只是开了个socks5的代理服务，至于怎么用这个socks5代理服务，什么流量用，完全看你如何配置了。

**Comment by yang-s-li** [comment]
这样说来我之前可能完全理解错了，根据 https://program-think.blogspot.com/2014/12/gfw-privoxy.html 的说明：

![image](https://cloud.githubusercontent.com/assets/20695423/17404009/cee116b0-5a8c-11e6-9d94-869791c23e84.png)

我以为Privoxy收到http请求并转发给socks5代理之后，代理服务器仍然可以在「pac自动代理模式」根据请求来源是否被墙决定流量是否需要被代理，所以我才反复询问，是否我的理解是错误的？

我其实只是纯粹的普通用户，对于工具背后的原理并不了解，使用过程中碰到问题就在网上查找解决方案，对于Privoxy+Shadowsocks的搭配，主要的目的就是：
- 把socks5代理转换为http代理，以便兼容尽可能多的应用程序
- 智能分流，减少流量消耗

如果方便的话，希望能详细讲解一下，非常感谢。

**Comment by yang-s-li** [comment]
我在Privoxy的配置就一句，也就是全部流量转发到socks5代理服务器：

`forward-socks5 / 127.0.0.1:1080 .`

**Comment by qiuyuzhou** [comment]
是的，你理解错了。建议你google下PAC自动代理的原理。
还有，NG的缺省socks5端口不是1080是1086，这是为了跟原版区别开来，避免潜在冲突，可以在高级设置中修改。
如果你不了解背后原理，还是不要进行这么复杂的配置，简单点只用ShadowsocksX-NG。
对普通用户socks5代理就够了，有些人要用http代理是因为一些命令行程序（wget，curl，git等等）只能使用http代理，都是专业搞开发的人才需要，普通用户又用不到。

**Comment by qiuyuzhou** [comment]
- 智能分流靠pac模式就可以了
- 对普通用户，socks5代理足够了

Keep simple and stupid.

**Comment by yang-s-li** [comment]
非常感谢你的耐心解答。

- 我仔细看过NG的readme，知道NG的默认端口是1086，原版的是1080，需要的时候我会修改。
- 我恰好需要用到你说的这些命令行程序（正在学习前端开发），还有Google Drive，所以必须有http代理。
- 目前我的配置基本能够满足日常需要，主要是NG相对用了很久的原版SS有一些区别，所以才有这个Issue，现在可以关闭了，再次致谢。

**Comment by coronin** [comment]
普通用户，开了sock5 1086，是可以关闭掉http 1087的吧？里面的 follow globel mode 是不是应该 global mode？开关的含义是什么？

**Comment by aishuidedabai** [comment]
PAC自动模式下。不能代理telegram等mac客户端。只能全局模式，请问怎么解决，因为全局会导致国内变慢

**Comment by timothyqiu** [comment]
@aishuidedabai I'm afraid that this is off topic. Please refer to issue #290 for help.

**Comment by ZhaorongHan** [comment]
我的环境是mac，chrome+SwitchyOmega插件：
我的疑问是：
       shadowsocksX-NG 使用PAC模式，这时我的浏览器可以切换代不代理，那我的系统级的软件使用的流量数据是经过pac判断的吗？
