### ISSUE TITLE
刚刚测试10.10.5 不能正常翻

### ISSUE THREAD

**Issue by ztechie** [qiuyuzhou/ShadowsocksX-NG#4]
刚刚测试10.10.5 不能正常翻 日本vps

**Comment by qiuyuzhou** [comment]
请将高级设置中本地监听地址中localhost改成127.0.0.1，然后再试一下

谢谢

在 2016年6月14日，下午3:52，ztechie <notifications@github.com> 写道：

刚刚测试10.10.5 不能正常翻 日本vps

**Comment by ztechie** [comment]
下载了新版本ok了（新版本是127.0.0.1） 扫描二维码什么的都测试了。暂时没发现问题。再次谢谢作者
