### ISSUE TITLE
能不能通过命令行更新 Server 配置

### ISSUE THREAD

**Issue by ElfSundae** [qiuyuzhou/ShadowsocksX-NG#40]
更新密码

**Comment by qiuyuzhou** [comment]
目前没有想到简单的方法实现。

**Comment by ElfSundae** [comment]
用 JSON 可以吗？比如

```
$ /Applications/ShadowsocksX-NG.app/Contents/MacOS/ShadowsocksX-NG addserver "json config"
$ ShadowsocksX-NG updateserver "address_or_remark" "json config"
$ ShadowsocksX-NG  removeserver "address_or_remark"

$ ShadowsocksX-NG server -add "remark" --json="..."
$ ShadowsocksX-NG server -add "remark" --server_host="" --server_port="" --password="" --encrypt_method="rc4"
$ ShadowsocksX-NG server -update "remark" --password="new"
$ ShadowsocksX-NG server -update "remark" --json="..."
$ ShadowsocksX-NG server -remove "remark"
$ ShadowsocksX-NG server -remove --server_host="abc.com"
$ ShadowsocksX-NG server -list
```

**Comment by qinyuhang** [comment]
我在分支加了一个[批量导入导出配置json文件](https://github.com/qinyuhang/ShadowsocksX-NG/tree/import-json-configs)（json配置文件兼容win版），你的这个情况我感觉可以通过：
导出json文件 -> 命令行批量修改json文件密码 -> 重新导入 -> 删除旧的服务器配置 来达成。

**Comment by ElfSundae** [comment]
@qinyuhang 谢谢，刚试了下，好像也是在菜单里操作，不支持命令行。

**Comment by qinyuhang** [comment]
没说可以支持在命令行执行……

Elf Sundae <notifications@github.com>于2016年8月30日 周二10:03写道：

**Comment by ElfSundae** [comment]
我之前买过几个年付ss账号，服务器被和谐后老板就跑路了 😞  现在主要用 Google hosts，也不常用ss了，偶尔用的话就去找个免费的用。
免费账号基本都会不停改密码，所以最初的想法是看这个能不能支持自动配置服务器信息，我写个脚本爬密码然后放到 crontab 里，要有时就不用去改密码了。
小问题，不用管了 😄

**Comment by qinyuhang** [comment]
额 这个你可以自己写AppleScript达成的

Elf Sundae <notifications@github.com>于2016年8月30日 周二10:10写道：

**Comment by ElfSundae** [comment]
嗯，应该可以，谢谢提醒。
