### ISSUE TITLE
Twitter和tweetbot客户端PAC代理模式没法访问

### ISSUE THREAD

**Issue by kingjoydom** [qiuyuzhou/ShadowsocksX-NG#42]
在PAC代理的模式下Twitter客户端或者tweetbot客户端都没办法FQ，但是Twitter网页版却是可以访问。全局情况下都可以访问，哪位哥哥知道怎么设置可以让代理模式下也可以访问啊？

**Comment by qinyuhang** [comment]
这个很有可能和 https://github.com/qiuyuzhou/ShadowsocksX-NG/issues/30 的问题是一样的

**Comment by kingjoydom** [comment]
我看了一下#30 的问题，估计是的。我的系统现在是10.12的。手贱啊，真不该升级的。

**Comment by qinyuhang** [comment]
我自己做了一个补丁，今晚会发一个PR过来，如果这边没有merge，明天我自己的源会merge这个补丁的，不用着急，这两天大概就能解决。

**Comment by kingjoydom** [comment]
太感谢，期待！现在真的是太不方便了！

**Comment by qinyuhang** [comment]
已经发了PR https://github.com/qiuyuzhou/ShadowsocksX-NG/pull/43 ，如果没有merge请参考我的源 https://github.com/qinyuhang/ShadowsocksX-NG/tree/webserver

**Comment by qinyuhang** [comment]
@kingjoydom 给你打包了一个，你试试？https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.2

**Comment by kingjoydom** [comment]
我试试，马上告诉你

**Comment by kingjoydom** [comment]
好像不可以，而且我用PAC模式好像连chrome都没法访问了。。。全局倒是可以的。

**Comment by qinyuhang** [comment]
你检查一下 ～/.ShadowsocksX-NG下面有没有gfwlist.js呢？

光法 <notifications@github.com>于2016年8月23日 周二17:40写道：

**Comment by qinyuhang** [comment]
那我先撤回PR吧，等我回家用自己的10.12测试机测试一下先
秦宇航 <qinyuhangxiaoxiang@gmail.com>于2016年8月23日 周二17:42写道：

**Comment by kingjoydom** [comment]
有gfwlist.txt,没有gfwlist.js

**Comment by qinyuhang** [comment]
啊 这样啊 拷贝一份 gfwlist.txt为gfwlist.js即可。看来是这里我写错文件名了

光法 <notifications@github.com>于2016年8月23日 周二17:45写道：

**Comment by kingjoydom** [comment]
试了好像还是不可以。。。

**Comment by qinyuhang** [comment]
不是……说错了 需要一份gfwlist.js文件
秦宇航 <qinyuhangxiaoxiang@gmail.com>于2016年8月23日 周二17:53写道：

**Comment by kingjoydom** [comment]
你今天会重新打个版本吗？

**Comment by meritozh** [comment]
@qinyuhang 127.0.0.1:8090/proxy.pac文件并不存在。~/.shadowsocks-NG/gfwlist.js已有

**Comment by qinyuhang** [comment]
等我在自己测试机测试OK了会重新打开的

光法 <notifications@github.com>于2016年8月23日 周二18:53写道：

**Comment by qinyuhang** [comment]
我已经重新改好了请 @kingjoydom @meritozh 两位帮忙测试一下，谢谢。 https://github.com/qinyuhang/ShadowsocksX-NG/files/432302/ShadowsocksX-NG.app-Fix.zip

**Comment by kingjoydom** [comment]
好像可以了，我已经没有问题了

**Comment by meritozh** [comment]
没问题了

**Comment by qinyuhang** [comment]
好的 重开了 PR 了
merito <notifications@github.com>于2016年8月23日 周二19:56写道：

> 没问题了

**Comment by kingjoydom** [comment]
为啥PAC场景下Telegram也不可以了啊。。。。。。

**Comment by qinyuhang** [comment]
你用的是那个版本的呢？是这个修改的版本吗？可有其他的详细信息？比如是否存在~/.ShadowsocksX-NG/gfwlist.js 或者系统设置里面代理的情况，或者log？

**Comment by kingjoydom** [comment]
![Uploading 截图 2016-08-24 14时02分58秒.jpg…]()

**Comment by kingjoydom** [comment]
![image](https://cloud.githubusercontent.com/assets/20087455/17919968/fa9a3e40-6a03-11e6-9bde-99e367cc553b.png)

**Comment by qinyuhang** [comment]
你用的是TG for Mac原生版本么（bundle id: _**ru.keepcoder.Telegram**_）？
TG for Mac原生版本（ https://itunes.apple.com/cn/app/telegram/id747648890?mt=12&uo=4 ） 这两天已经彻底不行了，必须全局模式，我的TG也不行了。
现在可用的是 TG Desktop（bundle id: **_org.telegram.desktop_**）（ https://itunes.apple.com/cn/app/telegram-desktop/id946399090?mt=12&uo=4 ）需要手动设置代理（在软件的 settings > connection type > TCP with custom socks5-proxy）

**Comment by kingjoydom** [comment]
好吧，太感谢了。我之前使用的是原生的。我用你说的这个已经可以了。

**Comment by qiuyuzhou** [comment]
duplicate. #30
