### ISSUE TITLE
If enable UDP relay. 怎么用起来 ，不是很明白

### ISSUE THREAD

**Issue by ztechie** [qiuyuzhou/ShadowsocksX-NG#5]
If enable UDP relay. 怎么用起来 ，不是很明白

**Comment by qiuyuzhou** [comment]
就是开启UDP协议的代理。个人认为没什么用。不是所有服务器都支持。好像只有shadowsocks-libev实现了。高级功能，不明白，不用管，也不要改设置。

**Comment by qiuyuzhou** [comment]
## 决议：SwiftUI 菜单栏与配置管理界面信息架构

两轮 grilling 收口（领域词汇新增 **Listen scope（监听范围）**，已入 CONTEXT.md @ e3604e5）。

### 窗口与导航

- **单一主窗口**（SwiftUI `NavigationSplitView`）：分区为 服务器（分组树 + 详情编辑）/ 订阅 / 诊断 / 设置（常规 + 高级）。沿用旧式"Server Preferences + Preferences"双窗口的方案被否。
- App 为 LSUIElement：无 Dock 图标；关窗不退应用；从状态菜单重开主窗口；可达性按 SwiftUI/VoiceOver 标准语义 + 主窗口全键盘可达，不做特殊定制。

### 菜单栏状态菜单（快速操作白名单）

1. 头部状态摘要（运行中 + 当前模式 + 活动目标名）
2. 代理开/关切换（关闭即显式停止协议：删运行时配置、停止代理；见 #10）
3. 代理模式选择（PAC / 全局 / 手动 / 外部 PAC，勾选态）
4. 活动目标选择器：分组树以**级联子菜单**呈现，选服务器=激活该服务器，选分组=激活分组（#8 语义）；菜单中只读，不可编辑
5. 立即更新全部订阅
6. HTTP 代理导出行复制（按当前监听范围生成 127.0.0.1 或主机地址行）
7. 打开主窗口
8. 退出（**仅退出 GUI，代理继续运行**，菜单项明示"代理仍在后台运行"）

所有编辑类操作（增删改服务器/分组、订阅 URL、拖拽）只进主窗口。

### 主窗口各分区

- **服务器树**：单棵树呈现手动分组与订阅固定分组；订阅子树只读（不可拖拽/改结构/改字段，仅保留启用开关）；行内启用 checkbox；右键：激活 / 启用·禁用 / 重命名 / 新建分组 / 移动 / 删除（非空手动组二次确认）；拖拽移动，跨来源拒绝；详情表单字段沿用旧版：地址、端口、加密、密码、备注、插件、插件参数。
- **订阅**：每条订阅一卡片：名称、URL host、状态（正常/过期/失败+原因）、上次刷新时间、服务器数；操作：立即更新（单个/全部）、编辑 URL（保留身份，#9）、删除（二次确认）；新建 = 粘贴 URL。
- **导入/分享**（主窗口内）：剪贴板 ss://、导入 URL…、**从图片识别二维码**（文件选择 + 拖图入窗；**屏幕扫码不做**，避免屏幕录制敏感权限）；分享在详情区（二维码弹窗 + 复制 ss://）。
- **诊断**：日志查看 + 导出诊断，收进主窗口，菜单不单列。

### 代理模式与监听

- 四模式：PAC / 全局 / 手动 / 外部 PAC（外部 PAC 依 #11 实测结果，失败则菜单隐藏该项）。
- HTTP 监听为与模式正交的独立开关（sslocal 混合入站直接提供 HTTP/SOCKS5，无 Privoxy）。
- **监听范围（新增，继承并扩展 #11/#10）**：设置中两态切换——回环（默认）/ 主机地址；**同时约束** PAC HTTP endpoint 绑定与 sslocal SOCKS5/HTTP 入站绑定（共享单一 scope，保证分享出去的 PAC URL 总指向可达代理）。主机态绑定通配地址（0.0.0.0），PAC 内容中的 proxy 行、PAC URL 复制、HTTP 导出行均使用本机网络地址；端口仍由用户配置；切到主机态时 UI 明示"代理将无鉴权地对局域网开放"。

### 设置分区

- 常规：登录时启动 GUI（默认开）、两个全局快捷键（开关代理 / 切换模式，用 [KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts) 实现，可自定义）、UDP 中继、超时、verbose。
- 高级：SOCKS5 与 HTTP 监听端口、监听范围切换、绕过列表、外部 PAC URL、GFW List URL、PAC 本地端口、重置偏好；PAC 用户规则内嵌文本编辑器。

### 错误 / 权限 / 迁移

- 三层呈现：菜单栏图标状态（灰=停、黑=运行、角标=异常）；菜单头部状态行 + 主窗口横幅（错误可展开详情）；触发处 inline 提示（带"打开系统设置"按钮）。
- 后台订阅刷新失败**不发系统通知**：仅标过期/失败状态 + 窗口横幅（上次快照仍在服务，#9）。
- 迁移：首启检测到旧版配置时弹窗询问"导入旧版 N 台服务器？"，确认后迁为独立手动分组（保留 UUID，#8）；可跳过，主窗口留"从旧版导入"入口。

### 明确不做（本版）

- 屏幕扫码（屏幕录制权限）——以二维码图片识别替代。
- 检查更新（旧版本实为跳转 GitHub Releases，非 Sparkle；2.0 首版不做）。
- 网络接口控制（系统代理写所有活动网络服务，后续有需求再加）。
