### ISSUE TITLE
能不能搞个扁平化的图标

### ISSUE THREAD

**Issue by ztechie** [qiuyuzhou/ShadowsocksX-NG#6]
能不能搞个扁平化的图标，作者幸苦

**Comment by qiuyuzhou** [comment]
不擅长搞图标，用的图标还是以前原作者的版本。
这要看有没有搞艺术的人贡献下？

**Comment by ztechie** [comment]
贡献了，换一下吧，幸苦你了，在附件





在 2016-06-21 16:07:34，"Qiu Yuzhou" <notifications@github.com> 写道：


不擅长搞图标，用的图标还是以前原作者的版本。
这要看有没有搞艺术的人贡献下？

**Comment by ztechie** [comment]
**https://www.dropbox.com/s/xjdcx3dglymewqd/AppIcon.appiconset.zip?dl=0** 图标下载地址

**Comment by qiuyuzhou** [comment]
78bb0b7d32d9aa423dc6f3ab2e03f84e50403dd9
