### ISSUE TITLE
直接退出后ss-local还在运行，网络代理设置也在存在

### ISSUE THREAD

**Issue by ztechie** [qiuyuzhou/ShadowsocksX-NG#7]
直接退出后ss-local还在运行，网络代理设置也在存在，必须要停止后在在退出才可以.这个是问题吗

**Comment by qiuyuzhou** [comment]
目前设计就是这样，看Readme
[Diferences with orignal ShadowsocksX](https://github.com/qiuyuzhou/ShadowsocksX-NG#diferences-with-orignal-shadowsocksx)

**Comment by qiuyuzhou** [comment]
是作为后台服务运行的，launchd

**Comment by qiuyuzhou** [comment]
占用不到1M内存，没什么影响，不用在意
