### ISSUE TITLE
希望提供网络选择功能

### ISSUE THREAD

**Issue by eyvallah** [qiuyuzhou/ShadowsocksX-NG#9]
我是学校拨VPN上网，在网络设置里面第一个是以太网（访问学校内网），第二个是作热点分享的wifi，第三个是VPN连接，在shadowsocks里面切换模式后，代理设置只应用在第一个也就是以太网里面，希望能够提供设定网络选择的功能。

服务顺序里面修改了以太网还是会回到第一个......

**Comment by qiuyuzhou** [comment]
研究了下。
发现现在使用的接口遍历不到VPN的项，也不能修改VPN的相应配置。所以，暂时没办法满足你的需要。
如果谁知道该怎么做，请告诉我，谢谢。

```
SCPreferencesRef prefRef = SCPreferencesCreate(nil, CFSTR("Shadowsocks"), nil);
 NSDictionary *sets = (__bridge NSDictionary *)SCPreferencesGetValue(prefRef, kSCPrefNetworkServices);
```
取得的数据不包括VPN配置

**Comment by qiuyuzhou** [comment]
又研究了下，发现PPTP和L2TP类型VPN可以取到。
IKEv2类型的VPN取不到。

**Comment by eyvallah** [comment]
我是L2TP(IPSec)的。可能是因为开了网络共享的原因不能找到？

**Comment by qiuyuzhou** [comment]
不是这样。以前是根据类型判断。只修改以下类型的：

- AirPort
- Wi-Fi
- Ethernet

不好将VPN加入

**Comment by qiuyuzhou** [comment]
@eyvallah 你是否试过手工修改VPN的代理设置，是否能正常使用shadowsocks代理？

**Comment by eyvallah** [comment]
手动填写可以正常使用shadowsocks，记得以前用lantern的时候lantern能够正确给VPN添加代理，不过safari等应用网络会出现问题，要sudo killall -9 networks解决。能不能提供一个选项，列出所有网络，选定ss代理的网络

**Comment by qiuyuzhou** [comment]
@eyvallah 你自己试一下 feature/adv_proxy_conf 分支。

**Comment by qiuyuzhou** [comment]
Merged to branch develop.
