### ISSUE TITLE
请问如何设置才能真正的全局走代理 包括局域网

### ISSUE THREAD

**Issue by zanjie1999** [qiuyuzhou/ShadowsocksX-NG#925]
我这里拿ss做vpn来用了,用来访问远方的局域网
用手机做过测试,全局(包括局域网)的时候是可以正常访问的
在这里我即使设置了全局模式局域网ip还是不会走代理

目前在用户pac规则加了一条暂时用着

**Comment by txdywy** [comment]
去搜google的jigsaw的outline mac客户端😁

Sparkle <notifications@github.com> 于 2018年10月9日周二 21:21写道：
